### ISSUE TITLE
Broken already setted up Samba shares

### ISSUE THREAD

**Issue by andriy2** [beta-tester/RPi-PXE-Server#12]
After installing PXE Server my setted up samba shares was lost!

**Comment by beta-tester** [comment]
sorry for that...
yes, at the moment i assumed a new fresh virgin raspbian installation.
so i cut away everything, that is comming after the
`#======================= Share Definitions =======================` comment in the /etc/samba/smb.conf file and add shares  for /srv and /media...
then better i will keep existing settings and simply add my stuff.

**Comment by beta-tester** [comment]
i just changed that behavior in the master branch...
but there are more config files that will be simply replaces instead of reconfigured for simplicity.
even more in the testing branch - there i don't take care for anything - that is my personal testing branch.

i added some addition hints to the readme file, that things will be overridden.
