### ISSUE TITLE
Feature Request: Automated Install using preseed

### ISSUE THREAD

**Issue by squadramunter** [beta-tester/RPi-PXE-Server#20]
I like to use this RPi-PXE-Server using an automated installer. Maybe you can implement this as an optional feature?

https://www.hiroom2.com/2017/06/29/debian-9-install-pxe-boot-server-for-automated-install/ 

U used this link to know how the preseed is configured. There are plenty more sites that explain how to enable preseeds for each distro.

**Comment by beta-tester** [comment]
hello @squadramunter ,
i am not sure how i could implement that kind of feature to the script, because everybody will have a different need for installing a distro.

i think that option has to be made by everyone who will use it.
on ubuntu there is an APPEND boot menu  parameter `file=/cdrom/preseed/ubuntu.seed` that will point to a preseed script i think. and for debian there will be a similar parameter to  point to a preseed or kickstarter script i think.
the only problem i see is, that the preseed or kickstart script can not be loaded from a different location than the initrd, squashfs or the ISO-image.

i mount and populate the ISO images directly and readonly, to do not waste too much memory/diskspace.

you may need to "_overlay_" the initrd or the file system to get your preferred file to that same location.

if the preseed file can be located on any location NFS, SMB, TFTP, HTTP, then i don't see a reason, why it could not be possibl to add your own preseed/kickstart script to the PXE boot menu.
