### ISSUE TITLE
Additional file for customizations

### ISSUE THREAD

**Issue by frchico** [beta-tester/RPi-PXE-Server#30]
Could it include calls to scripts that we customize? This way it would be easier to add our features and synchronize with the project updates.

In #22 you show some commands, though which file should they be included in?

Anyway, thanks for the project!

**Comment by beta-tester** [comment]
i have no plan to do such a change... sorry.

to me, it would mean to review/redesign/rewrite everything.

by splitting the project in separate p2-include files, i already tried to make the project more customizable, but for more i have no time at the moment.

for customization, the most intresting files are

- **p2-include-url.sh**
that contains the uniqe label for live OS'es, and the url to the iso/image to download.

- **p2-include-handle.sh**
that contains what live OS'es will be handled

- **p2-include-menu.sh**
that contains the pxe-menu entry for the live OS'es. this is the trickiest part, because each live OS can have different requirements. and not all Live OS'es are able to PXE boot out of the box without changing their boot files.

- **p2-include-var.sh**
that contains alot of variables, for example for custom languages - in case the live OS does support language settings. for me it is set up to **de**, **de_DE**,... for **Germany**.

when you re-run the install-pass2 script, it will read the p2-include files and install/uninstall (handle/unhandle) iso/images according the changes made in those files.

BTW: if you cloned my project the last 5 days, there was a mistake in the project, i fixed today.
